#!/bin/bash

SEL="$(cat ~/.bookmarks | dmenu)"

OPT="$(printf "$SEL" | grep -o '^[A-Z] ' | cut -d ' ' -f1)"
URL="$(printf "$SEL" | grep -o '[^ ]*$')"

case "$OPT" in
    T)
        PROXY="socks://127.0.0.1:9050"
        ;;
    *)
        ;;
esac

test -z "$URL" && exit

http_proxy="$PROXY" surf "$URL"
shred ~/.surf/cookies.txt
rm ~/.surf/cookies.txt
rm -r ~/.surf/cache
