#!/bin/bash

if [ "$#" == "0" ] ; then
    FILE="$(find -name '*' -type f | choice)"
else
    FILE="$(find -name "$1" -type f | choice)"
fi

if [ "$?" == "2" ] ; then
    printf "User cancelled\n"
    exit 0
fi

if [ -f "$FILE" ] ; then
    $EDITOR "$FILE"
else
    printf "No such file: $FILE\n"
fi
