#!/bin/bash

res="$(grep -rnIH --exclude "tags" --exclude-dir ".git" "$*" | sed 's/:/ /' | choice -s ":" -d $'\e[34m%k\e[39m: %v')"
[ -z "$res" ] && exit
read -r file line <<< "$res"
test -f "$file" && vim "$file" +"$line"
